baseURL = 'cloud-native-shenzhen.github.io'
languageCode = 'en-us'
title = 'Cloud Native Shenzhen'
theme = 'ananke'
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
